name: shelf_hotreload
description: Wrapper to easily enable hot-reload for shelf applications.
version: 1.1.0
repository: https://github.com/felixblaschke/shelf_hotreload

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  hotreloader: ^3.0.2
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
