name: shelf_hotreload
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/felixblaschke/shelf_hotreload

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hotreloader: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
