name: shelf_hotreload
description: Wrapper to easily enable hot-reload for shelf applications.
version: 1.2.0
repository: https://github.com/felixblaschke/shelf_hotreload

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  hotreloader: ^3.0.4
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.0
  shelf: ^1.3.0
